---

- hosts: all
  become: true
  tasks:

  - name: update
    dnf:
      update_cache: yes
   
  - name: install apache2
    dnf:
      name: httpd
      state: latest
  
  - name: add php support for apache
    dnf:
      name: php, php-common, php-pecl-apcu, php-cli
      state: latest
